name: Homebrew Tap Sync

on:
  push:
    tags:
      - '*'

jobs:
  sync-homebrew-tap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Homebrew tap version sync
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HOMEBREW_SYNC_REPO_PAT }}
          repository: alesbrelih/homebrew-gitlab-ci-ls
          event-type: version-update
          client-payload: |
            {
              "version": "${{ github.ref_name }}",
              "source_repo": "${{ github.repository }}"
            }
